name: Build Nuitka OneFile App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build with Nuitka --onefile
        run: |
          python -m nuitka --onefile --enable-plugin=tk-inter --output-dir=dist main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-Linux-x64
          path: dist/main.bin

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4


   
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build with Nuitka --onefile
        run: |
          python -m nuitka --onefile --enable-plugin=tk-inter --assume-yes-for-downloads --output-dir=dist main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-Windows-x64
          path: dist/main.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build with Nuitka --onefile
        run: |
          python -m nuitka --onefile --enable-plugin=tk-inter --output-dir=dist main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-macOS-x64
          path: dist/main.bin
